src/Entity/Leader.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LeaderRepository")
 */
class Leader
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="integer")
     */
    private $Age;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ethnie", inversedBy="leaders")
     */
    private $Ethnie;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Parti", inversedBy="leaders")
     */
    private $Parti;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Nation", mappedBy="Leader", cascade={"persist", "remove"})
     */
    private $nation;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Photo;

    public function __construct()
    {
        $this->Traits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->Age;
    }

    public function setAge(int $Age): self
    {
        $this->Age = $Age;

        return $this;
    }

    /**
     * @return Collection|TraitElement[]
     */
    public function getTraits(): Collection
    {
        return $this->Traits;
    }

    public function addTrait(TraitElement $trait): self
    {
        if (!$this->Traits->contains($trait)) {
            $this->Traits[] = $trait;
        }

        return $this;
    }

    public function removeTrait(TraitElement $trait): self
    {
        if ($this->Traits->contains($trait)) {
            $this->Traits->removeElement($trait);
        }

        return $this;
    }

    public function getEthnie(): ?Ethnie
    {
        return $this->Ethnie;
    }

    public function setEthnie(?Ethnie $Ethnie): self
    {
        $this->Ethnie = $Ethnie;

        return $this;
    }

    public function getParti(): ?Parti
    {
        return $this->Parti;
    }

    public function setParti(?Parti $Parti): self
    {
        $this->Parti = $Parti;

        return $this;
    }

    public function getNation(): ?Nation
    {
        return $this->nation;
    }

    public function setNation(Nation $nation): self
    {
        $this->nation = $nation;

        // set the owning side of the relation if necessary
        if ($nation->getLeader() !== $this) {
            $nation->setLeader($this);
        }

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->Photo;
    }

    public function setPhoto(?string $Photo): self
    {
        $this->Photo = $Photo;

        return $this;
    }
}

src/Entity/Nation.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NationRepository")
 */
class Nation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Libelle;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\NationParti", mappedBy="relation", cascade={"persist", "remove"})
     */
    private $nationPartis;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ethnie", inversedBy="nations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Ethnie;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Leader", inversedBy="nation", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $Leader;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Drapeau;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Effet", inversedBy="nations")
     */
    private $Effets;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    public function __construct()
    {
        $this->nationPartis = new ArrayCollection();
        $this->Effets = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->Libelle;
    }

    public function setLibelle(string $Libelle): self
    {
        $this->Libelle = $Libelle;

        return $this;
    }

    /**
     * @return Collection|NationParti[]
     */
    public function getNationPartis(): Collection
    {
        return $this->nationPartis;
    }

    public function addNationParti(NationParti $nationParti): self
    {
            $this->nationPartis[] = $nationParti;
            $nationParti->setRelation($this);

        return $this;
    }

    public function removeNationParti(NationParti $nationParti): self
    {
        if ($this->nationPartis->contains($nationParti)) {
            $this->nationPartis->removeElement($nationParti);
            // set the owning side to null (unless already changed)
            if ($nationParti->getRelation() === $this) {
                $nationParti->setRelation(null);
            }
        }

        return $this;
    }

    public function removeNationPartis(): self
    {
            $this->nationPartis = null;
            return $this;
    }

    public function getEthnie(): ?Ethnie
    {
        return $this->Ethnie;
    }

    public function setEthnie(?Ethnie $Ethnie): self
    {
        $this->Ethnie = $Ethnie;

        return $this;
    }

    public function getLeader(): ?Leader
    {
        return $this->Leader;
    }

    public function setLeader(Leader $Leader): self
    {
        $this->Leader = $Leader;

        return $this;
    }

    public function getDrapeau(): ?string
    {
        return $this->Drapeau;
    }

    public function setDrapeau(?string $Drapeau): self
    {
        $this->Drapeau = $Drapeau;

        return $this;
    }

    /**
     * @return Collection|Effet[]
     */
    public function getEffets(): Collection
    {
        return $this->Effets;
    }

    public function addEffet(Effet $effet): self
    {
        if (!$this->Effets->contains($effet)) {
            $this->Effets[] = $effet;
        }

        return $this;
    }

    public function removeEffet(Effet $effet): self
    {
        if ($this->Effets->contains($effet)) {
            $this->Effets->removeElement($effet);
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

}

src/Entity/Parti.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PartiRepository")
 */
class Parti
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Libelle;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Politique", inversedBy="partis")
     */
    private $Politique;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Logo;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Leader", mappedBy="Parti")
     */
    private $leaders;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Nation")
     */
    private $nations;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\NationParti", inversedBy="Parti", cascade={"persist", "remove"})
     */
    private $nationParti;

    public function __construct()
    {
        $this->leaders = new ArrayCollection();
        $this->nations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->Libelle;
    }

    public function setLibelle(string $Libelle): self
    {
        $this->Libelle = $Libelle;

        return $this;
    }

    public function getPolitique(): ?Politique
    {
        return $this->Politique;
    }

    public function setPolitique(?Politique $Politique): self
    {
        $this->Politique = $Politique;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->Logo;
    }

    public function setLogo(?string $Logo): self
    {
        $this->Logo = $Logo;

        return $this;
    }

    /**
     * @return Collection|Leader[]
     */
    public function getLeaders(): Collection
    {
        return $this->leaders;
    }

    public function addLeader(Leader $leader): self
    {
        if (!$this->leaders->contains($leader)) {
            $this->leaders[] = $leader;
            $leader->setParti($this);
        }

        return $this;
    }

    public function removeLeader(Leader $leader): self
    {
        if ($this->leaders->contains($leader)) {
            $this->leaders->removeElement($leader);
            // set the owning side to null (unless already changed)
            if ($leader->getParti() === $this) {
                $leader->setParti(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Nation[]
     */
    public function getNations(): Collection
    {
        return $this->nations;
    }

    public function addNation(Nation $nation): self
    {
        if (!$this->nations->contains($nation)) {
            $this->nations[] = $nation;
            $nation->addParti($this);
        }

        return $this;
    }

    public function removeNation(Nation $nation): self
    {
        if ($this->nations->contains($nation)) {
            $this->nations->removeElement($nation);
            $nation->removeParti($this);
        }

        return $this;
    }

    public function getNationParti(): ?NationParti
    {
        return $this->nationParti;
    }

    public function setNationParti(NationParti $nationParti): self
    {
        $this->nationParti = $nationParti;

        // set the owning side of the relation if necessary
        if ($nationParti->getParti() !== $this) {
            $nationParti->setParti($this);
        }

        return $this;
    }
}

src/Controller/NationController.php
<?php

namespace App\Controller;

use App\Dal\Nation_Parti_factory;
use App\Entity\Nation;
use App\Entity\NationParti;
use App\Form\NationType;
use App\Form\NationTypeEditMode;
use App\Repository\LeaderRepository;
use App\Repository\NationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class NationController extends AbstractController
{
    /**
     * @Route("/nation", name="nation")
     */
    public function index()
    {
        return $this->render('nation/index.html.twig', [
            'controller_name' => 'NationController',
        ]);
    }

    /**
     * @Route("/nation/build", name="nationBuild")
     */
    public function create(Request $request) {
        $nation = new Nation();
        $form = $this->createForm(NationType::class,$nation,array('label' => 0));
        $form->handleRequest($request);
        $entityManager = $this->getDoctrine()->getManager();
        if ($form->isSubmitted() && $form->isValid()) {
            $lesPartis = $nation->getNationPartis();
            $nation->removeNationPartis();
            foreach ($lesPartis as $parti) {
                $nationParti = new NationParti();
                $nationParti->setParti($parti);
                $nationParti->setPopularite(1);
                $nation->addNationParti($nationParti);

            }

            $entityManager->persist($nation);
            $entityManager->flush();
            return $this->redirectToRoute("nationview", ["id" => $nation->getId()]);
        } else {
            return $this->render('nation/form.html.twig', [
                'controller_name' => 'NationController',
                'form' => $form->createView()
            ]);
        }

    }

    /**
     * @Route("/nation/edit/{id}", name="nationedit")
     */
    public function edit(int $id, Request $request, NationRepository $repoNation) {
        $nation = $repoNation->find($id);
        $nationSaved = $nation;
        if($nation) {
            $form = $this->createForm(NationType::class,$nation, array('label'=>$nation->getLeader()->getId()));
            $nationArray = $request->request->get('nation');
            if(!isset($nationArray['Leader'])) {
                $nationArray['Leader'] = $nationSaved->getLeader();
                $request->request->set('nation',$nationArray);
            }
            $form->handleRequest($request);
            if ($form->isSubmitted()) {
                // On transforme les objets "Parti" en objets Nation_Parti
                $lesPartis = $nation->getNationPartis();
                $nation->removeNationPartis();
                foreach ($lesPartis as $parti) {
                    $nationParti = new NationParti();
                    $nationParti->setParti($parti);
                    $nationParti->setPopularite(1);
                    $nation->addNationParti($nationParti);

                }
                //Nettoyage des anciennes relations NM
                $nation_partiFactory = new Nation_Parti_factory($this->getDoctrine()->getConnection());
                $nation_partiFactory->clearNationParti($nation);
                //Sauvegarde des nouvelles relations
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($nation);
                $entityManager->flush();
                return $this->redirectToRoute("nationview", ["id" => $nation->getId()]);
            } else {
                $return = $this->render('nation/form.html.twig', [
                    'form' => $form->createView()
                ]);
            }
        }
        return $return;
    }

    /**
     * @Route("/nation/view/{id}", name="nationview")
     */
    public function view(Int $id, NationRepository $repoNation) {
        $nation = $repoNation->find($id);
        if($nation) {
            return $this->render('nation/view.html.twig', [
                'nation' => $nation
            ]);
        } else {
            return $this->redirectToRoute("nationBuild");
        }
    }

    /**
     * @Route("/nation/remove/{id}", name="nationremove")
     */
    public function delete(Int $id, NationRepository $repoNation) {
        $nation = $repoNation->find($id);
        if($nation) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($nation);
            $entityManager->flush();
        }
        return $this->redirectToRoute("nationviewall");
    }

    /**
     * @Route("/nation/viewall", name="nationviewall")
     */
    public function viewAll(NationRepository $repoNation) {
        $nations = $repoNation->findAll();
        if($nations) {
            return $this->render('nation/viewall.html.twig', [
                'nations' => $nations
            ]);
        } else {
            return $this->redirectToRoute("nationBuild");
        }
    }
}

templates/nation/form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello NationController!{% endblock %}

{% block stylesheets %}
    {# 'app' must match the first argument to addEntry() in webpack.config.js #}


{% endblock %}

{% block body %}
<div class="container fontA p-3 my-3 text-center md ">
    {{ form_start(form,{'method': 'POST'}) }}
    <div class=" container p-3 my-3 text-center md ">
        <div class="form-group">
            {{ form_row(form.Libelle, { 'attr': {'class': 'form-control'} }) }}
        </div>
        <div class="form-group">
            {{ form_row(form.Description, { 'attr': {'class': 'form-control'} }) }}
        </div>
        <div class="form-group">
        {{ form_row(form.Ethnie, { 'attr': {'class': 'form-control selectpicker'} }) }}
        </div>
        <div class="form-group">
            {{ form_row(form.nationPartis, { 'attr': {'class': 'form-control selectpicker'} }) }}
        </div>
        <div class="form-group">
            {{ form_row(form.Effets, { 'attr': {'class': 'form-control selectpicker'} }) }}
        </div>
        <div class="form-group">
            {{ form_row(form.Leader, { 'attr': {'class': 'form-control selectpicker'} }) }}
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon3">https://siteImage/drapeau.png</span>
            </div>
            {{ form_widget(form.Drapeau|raw,  { 'attr': {'class': 'form-control'} }) }}
        </div>
        <div class="form-group">
            {{ form_row(form.submit, { 'attr': {'class': 'btn btn-primary'} }) }}
        </div>
    </div>
    {{ form_end(form) }}
</div>
    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
    {% endblock %}

{% endblock %}

templates/nation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello NationController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/wamp64/www/opposite_front_3/src/Controller/NationController.php'|file_link(0) }}">src/Controller/NationController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/wamp64/www/opposite_front_3/templates/nation/index.html.twig'|file_link(0) }}">templates/nation/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/nation/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PolitiqueController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="container fontA styleBlocCentral">
    <div class="barreBlocElement"><button type="button" class="btn btn-info"><a  href="{{  path('nationedit', {id:nation.id|number_format})}}">Editer</a></button><button type="button" class="btn btn-info"><a  href="{{ path('nationviewall')}}">Retour</a></button><button type="button" class="btn btn-info"><a  href="{{ path('nationremove', {id:nation.id|number_format})}}">Détruire</a></button></div>
    <h3 class="text-white">{{ nation.libelle }}</h3>
    <div class="row">
        <div class="container pb-4">
            {% for effet in nation.effets %}
                <img class="infoElement" id="{{ effet.id }}" alt="test" src="{{ effet.icone }}"/>
                <div class="infoBulle" id="bulle{{ effet.id }}">{{ effet.Description|raw }}
                    {% for trait in effet.TraitElements %}
                        <span style="color:{{ trait.couleur }};">{{ trait.libelle }}</span><br/>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
                <img src="{{ nation.leader.photo }}"> <i>{{ nation.leader.nom }} {{ nation.leader.prenom }}</i>
        </div>

        <div class="col-sm">
            <img class="profilePic" src="{{ nation.drapeau }}" /><i class="alignFlag">Drapeau national</i>
        </div>
        <div class="container pb-4">
            {{ nation.libelle }} est une nation liée au {{ nation.leader.parti.politique.libelle }}. Le parti au pouvoir est le {{ nation.leader.parti.libelle }}.
        <br/>
        <br/>
            {{ nation.Description|raw }}
        </div>
        <div class="container pb-4">
            <h4> Partis politiques actifs</h4>
            {% for nation_parti in nation.nationPartis %}
                <tr class="">
                    <td> <a href="{{ path('partiview', {id:nation_parti.parti.id}) }}"> {{ nation_parti.parti.Libelle }}</a></td>
                    <td><img height="24px" width="24px" src="{{ nation_parti.parti.logo }}"/></td>
                </tr>
            {% endfor %}
        </div>
    </div>





</div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script>
        $(".infoElement").mouseover(function() {
            $("#bulle"+this.id).show();
        });

        $(".infoElement").mouseleave(function() {
            $("#bulle"+this.id).hide();
        });
    </script>
{% endblock %}

templates/nation/viewall.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PolitiqueController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="container fontA styleBlocCentral">
    <div class="barreBlocElement"><button type="button" class="btn btn-primary m-2"><a  href="{{ path('nationBuild')}}">Ajouter un pays</a></button></div>

    <h3>Nations</h3>
    <div class="container">
        {% for nation in nations %}
            <tr class="">
                <td> <a href="{{ path('nationview', {id:nation.id}) }}"> {{ nation.Libelle }}</a></td>
                <td><img height="24px" width="24px" src="{{ nation.drapeau }}"/></td>
            </tr>
        {% endfor %}

    </div>


</div>
{% endblock %}