src/Entity/Effet.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EffetRepository")
 */
class Effet
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Libelle;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;


    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $icone;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\TraitElement")
     */
    private $TraitElements;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Nation", mappedBy="Effets")
     */
    private $nations;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->Libelle;
    }

    public function setLibelle(string $Libelle): self
    {
        $this->Libelle = $Libelle;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function __construct()
    {
        $this->TraitElements = new ArrayCollection();
        $this->nations = new ArrayCollection();
    }


    public function getIcone(): ?string
    {
        return $this->icone;
    }

    public function setIcone(?string $Icone): self
    {
        $this->icone = $Icone;

        return $this;
    }

    /**
     * @return Collection|TraitElement[]
     */
    public function getTraitElements(): Collection
    {
        return $this->TraitElements;
    }

    public function addTraitElement(TraitElement $traitElement): self
    {
        if (!$this->TraitElements->contains($traitElement)) {
            $this->TraitElements[] = $traitElement;
        }

        return $this;
    }

    public function removeTraitElement(TraitElement $traitElement): self
    {
        if ($this->TraitElements->contains($traitElement)) {
            $this->TraitElements->removeElement($traitElement);
        }

        return $this;
    }

    /**
     * @return Collection|Nation[]
     */
    public function getNations(): Collection
    {
        return $this->nations;
    }

    public function addNation(Nation $nation): self
    {
        if (!$this->nations->contains($nation)) {
            $this->nations[] = $nation;
            $nation->addEffet($this);
        }

        return $this;
    }

    public function removeNation(Nation $nation): self
    {
        if ($this->nations->contains($nation)) {
            $this->nations->removeElement($nation);
            $nation->removeEffet($this);
        }

        return $this;
    }

}

src/Entity/Leader.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LeaderRepository")
 */
class Leader
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="integer")
     */
    private $Age;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ethnie", inversedBy="leaders")
     */
    private $Ethnie;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Parti", inversedBy="leaders")
     */
    private $Parti;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Nation", mappedBy="Leader", cascade={"persist", "remove"})
     */
    private $nation;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Photo;

    public function __construct()
    {
        $this->Traits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->Age;
    }

    public function setAge(int $Age): self
    {
        $this->Age = $Age;

        return $this;
    }

    /**
     * @return Collection|TraitElement[]
     */
    public function getTraits(): Collection
    {
        return $this->Traits;
    }

    public function addTrait(TraitElement $trait): self
    {
        if (!$this->Traits->contains($trait)) {
            $this->Traits[] = $trait;
        }

        return $this;
    }

    public function removeTrait(TraitElement $trait): self
    {
        if ($this->Traits->contains($trait)) {
            $this->Traits->removeElement($trait);
        }

        return $this;
    }

    public function getEthnie(): ?Ethnie
    {
        return $this->Ethnie;
    }

    public function setEthnie(?Ethnie $Ethnie): self
    {
        $this->Ethnie = $Ethnie;

        return $this;
    }

    public function getParti(): ?Parti
    {
        return $this->Parti;
    }

    public function setParti(?Parti $Parti): self
    {
        $this->Parti = $Parti;

        return $this;
    }

    public function getNation(): ?Nation
    {
        return $this->nation;
    }

    public function setNation(Nation $nation): self
    {
        $this->nation = $nation;

        // set the owning side of the relation if necessary
        if ($nation->getLeader() !== $this) {
            $nation->setLeader($this);
        }

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->Photo;
    }

    public function setPhoto(?string $Photo): self
    {
        $this->Photo = $Photo;

        return $this;
    }
}

src/Form/LeaderType.php
<?php

namespace App\Form;

use App\Entity\Ethnie;
use App\Entity\Leader;
use App\Entity\Nation;
use App\Entity\Parti;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LeaderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Nom')
            ->add('Prenom')
            ->add('Age')
            ->add('Ethnie', EntityType::class, [
                'class' => Ethnie::class,
                'choice_label' => 'Libelle',
                'expanded' => false,
            ])
            ->add('Parti', EntityType::class, [
                'class' => Parti::class,
                'choice_label' => 'Libelle',
                'expanded' => false,
            ])
            ->add('Photo',UrlType::class)
            ->add('submit', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Leader::class,
        ]);
    }
}

src/Controller/LeaderController.php
<?php

namespace App\Controller;

use App\Entity\Leader;
use App\Entity\Parti;
use App\Form\LeaderType;
use App\Form\PartiType;
use App\Repository\LeaderRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class LeaderController extends AbstractController
{
    /**
     * @Route("/leader", name="leader")
     */
    public function index()
    {
        return $this->render('leader/index.html.twig', [
            'controller_name' => 'LeaderController',
        ]);
    }

    /**
     * @Route("/leader/build", name="leaderbuild")
     */
    public function form(Request $request) {
        $leader = new Leader();
        $form = $this->createForm(LeaderType::class,$leader);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($leader);
            $entityManager->flush();
            return $this->redirectToRoute("leaderview", ["id" => $leader->getId()]);
        } else {
            $return = $this->render('leader/form.html.twig', [
                'controller_name' => 'LeaderController',
                'form' => $form->createView()
            ]);
        }
        return $return;
    }



    /**
     * @Route("/leader/edit/{id}", name="leaderedit")
     */
    public function edit(int $id, Request $request, LeaderRepository $repoLeader) {
        $leader = $repoLeader->find($id);
        if($leader) {
            $form = $this->createForm(LeaderType::class,$leader);
            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($leader);
                $entityManager->flush();
                return $this->redirectToRoute("leaderview", ["id" => $leader->getId()]);
            } else {
                $return = $this->render('leader/form.html.twig', [
                    'controller_name' => 'PartiController',
                    'form' => $form->createView()
                ]);
            }
        }
        return $return;
    }

    /**
     * @Route("/leader/remove/{id}", name="leaderremove")
     */
    public function delete(Int $id, LeaderRepository $repoLeader) {
        $leader = $repoLeader->find($id);
        if($leader) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($leader);
            $entityManager->flush();
        }
        return $this->redirectToRoute("leaderremove");
    }

    /**
     * @Route("/leader/view/{id}", name="leaderview")
     */
    public function view(Int $id, LeaderRepository $repoLeader) {
        $leader = $repoLeader->find($id);
        if($leader) {
            return $this->render('leader/view.html.twig', [
                'leader' => $leader
            ]);
        } else {
            // error redirect on bug page
        }
    }

    /**
     * @Route("/leader/viewall", name="leaderviewall")
     */
    public function viewAll(LeaderRepository $repoLeader) {
        $leaders = $repoLeader->findAll();
        if($leaders) {
            return $this->render('leader/viewall.html.twig', [
                'leaders' => $leaders
            ]);
        } else {
            return $this->forward('App\Controller\LeaderController::form', [

            ]);
        }
    }

}

templates/leader/form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello NationController!{% endblock %}

{% block stylesheets %}
    {# 'app' must match the first argument to addEntry() in webpack.config.js #}


{% endblock %}

{% block body %}

<div class="container fontA p-3 my-3 text-center md fontA">
    <div class="barreBlocElement"><button type="button" class="btn btn-info"><a  href="{{ path('leaderviewall') }}">Retour</a></button></div>
    {{ form_start(form,{'method': 'POST'}) }}
        <div class="form-group">
            {{ form_row(form.Nom, { 'attr': {'class': 'form-control'} }) }}
        </div>
        <div class="form-group">
            {{ form_row(form.Prenom, { 'attr': {'class': 'form-control'} }) }}
        </div>
        <div class="form-group">
            {{ form_row(form.Age, { 'attr': {'class': 'form-control'} }) }}
        </div>
        <div class="form-group">
        {{ form_row(form.Parti, { 'attr': {'class': 'form-control selectpicker'} }) }}
        </div>
        <div class="form-group">
            {{ form_row(form.Ethnie, { 'attr': {'class': 'form-control selectpicker'} }) }}
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon3">https://siteImage/Logo.png</span>
            </div>
            {{ form_widget(form.Photo|raw,  { 'attr': {'class': 'form-control'} }) }}
        </div>
        <div class="form-group">
            {{ form_row(form.submit, { 'attr': {'class': 'btn btn-primary'} }) }}
        </div>
    {{ form_end(form) }}
</div>

    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
    {% endblock %}

{% endblock %}

templates/leader/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello LeaderController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/wamp64/www/opposite_front_3/src/Controller/LeaderController.php'|file_link(0) }}">src/Controller/LeaderController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/wamp64/www/opposite_front_3/templates/leader/index.html.twig'|file_link(0) }}">templates/leader/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/leader/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PolitiqueController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="container fontA styleBlocCentral">
    <div class="barreBlocElement"><button type="button" class="btn btn-info"><a  href="{{ path('politiqueviewAll')}}">Retour</a></button><button type="button" class="btn btn-info"><a  href="{{ path('leaderedit', {id:leader.id|number_format}) }}">Editer</a></button><button type="button" class="btn btn-info"><a  href="{{ path('leaderremove', {id:leader.id|number_format}) }}">Détruire</a></button></div>
    <h3 class="text-white">{{ leader.prenom }} {{ leader.nom }}</h3>
    <div class="row">
        <div class="col-sm">
            {{ leader.prenom }} {{ leader.nom }} est lié au <a href="{{ path('partiview', {id:leader.parti.id|number_format}) }}" >{{ leader.parti.libelle }}</a> <img height="57px" width="57px" src="{{ leader.parti.Logo }}"/>. Il est agé de {{ leader.age }} ans.
            <div class="container pb-4">


            </div>
        </div>
        <div class="col-sm">
            <img class="profilePic" src="{{ leader.photo }}" />
        </div>
    </div>





</div>
{% endblock %}

templates/leader/viewall.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PolitiqueController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="container fontA styleBlocCentral">
    <div class="barreBlocElement"><button type="button" class="btn btn-info"><a  href="{{ path('leaderbuild') }}">Nouveau leader</a></button></div>
    <h3 class="text-white">Leaders</h3>
    <div class="row">
        <div class="col-sm">
            <div class="container pb-4">
                {% for leader in leaders %}
                    <tr class="">
                        <td> <a href="{{ path('leaderview', {id:leader.id}) }}"> {{ leader.nom }} {{ leader.prenom }}</a></td>
                        <td><img height="24px" width="24px" src="{{ leader.photo }}"/></td>
                    </tr>
                {% endfor %}

            </div>
        </div>
    </div>





</div>
{% endblock %}